---
title: "Authorship and Contributions"
---

<br>

[Kaleb J. Frierson](https://kjf2152cumc.github.io/kfrierson.github.io/)

Kaleb is a second year MPH student in the Department of Epidemiology. His certificate is in Applied Biostatistics and Public Health Data Science. His contributions to this project included:

- Research question development and planning. 
- Collaborative brainstorming of data sources, cleaning procedures, exclusion criteria, and analyses given available data. 
- Development of the project website and primary authorship of the [project report](https://kjf2152cumc.github.io/nyslymedisease.github.io/project_report.html). 
- Using Tanmayi's maps to create the [Interactive Dashboard](https://kjf2152cumc.github.io/nyslymedisease.github.io/dashboard.html). 

[Mary N. Williams](https://www.linkedin.com/in/mary-williams106?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app)

Mary is a second year MPH student in the Department of Epidemiology. Her certificate is in Infectious Disease Epidimiology. Her contributions to this project included:

- Background research for question and development of question
- Collaboration on data sources, cleaning procedures, exclusion and inclusion criteria. 
- Created data analysis and described findings from the analysis for the [Results](https://kjf2152cumc.github.io/nyslymedisease.github.io/project_report.html). 

[Sarahy J. Martinez](https://www.linkedin.com/in/sarahy-martinez?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app)

Sarahy is a second year MPH student in the Department of Epidemiology. Her certificate is in Applied Biostatistics and Public Health Data Science. Her contributions to this project included: 

- Importing, cleaning, and tidying various data sources to create a final dataset for the team memebrs to conduct their analyses. 
- Assisted with scheduling days to meet and provided zoom links for all group meetings. 
- Assisted with developing the research topic and questions. 
- Brainstormed kinds of linear models and maps to create during analysis and visualization phase. 

[Tanmayi A. Amanchi](https://www.linkedin.com/in/tanmayi-amanchi-7895371b5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app) 

Tanmayi is a second year MPH student in the Department of Epidemiology, with a certificate in the Applied Biostatistics and Data Science. Her contributions to this project included:

- Research question development and project planning
- Organizing weather data from the [National Centers for Environmental Information](https://data.pnj.com/weather-data/new-york/36/1976-03-01/) to be easily read into R.
- Creating the interactive maps for the [Interactive Dashboard](https://kjf2152cumc.github.io/nyslymedisease.github.io/dashboard.html). 